/* Seed registry — in production this is an API over a signed, versioned
   manifest store; here it's data so the prototype runs from file://. */
const REGISTRY = [
  {
    id: 'code-reviewer', name: 'Code Reviewer Pro', version: '2.1.0',
    publisher: { name: 'DevTools Inc', verified: true },
    description: 'Reviews pull requests for correctness bugs, security issues and style drift, with inline suggested fixes.',
    category: 'coding', tags: ['review', 'git', 'quality'],
    capabilities: ['review pull requests', 'suggest fixes', 'enforce style guides'],
    model: 'claude-sonnet-5', permissions: ['repo:read', 'net:fetch'],
    pricing: { model: 'per_call', pricePerCall: 0.05 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 18400, ratings: { avg: 4.6, count: 320 }, updatedAt: '2026-06-20' },
  },
  {
    id: 'inbox-zero', name: 'Inbox Zero', version: '1.4.2',
    publisher: { name: 'Flowmail', verified: true },
    description: 'Triages your inbox: drafts replies, archives noise, and escalates anything that needs a human decision.',
    category: 'productivity', tags: ['email', 'triage'],
    capabilities: ['triage email', 'draft replies', 'summarize threads'],
    model: 'claude-haiku-4-5', permissions: ['email:read', 'email:send'],
    pricing: { model: 'subscription', monthly: 12 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 41200, ratings: { avg: 4.4, count: 1810 }, updatedAt: '2026-06-28' },
  },
  {
    id: 'deep-researcher', name: 'Deep Researcher', version: '3.0.1',
    publisher: { name: 'Atlas Labs', verified: true },
    description: 'Multi-source research with citations: fans out searches, cross-checks claims, and returns a sourced brief.',
    category: 'research', tags: ['research', 'citations', 'web'],
    capabilities: ['web research', 'fact checking', 'cited reports'],
    model: 'claude-fable-5', permissions: ['net:fetch'],
    pricing: { model: 'per_call', pricePerCall: 0.4 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 9800, ratings: { avg: 4.8, count: 540 }, updatedAt: '2026-06-15' },
  },
  {
    id: 'support-pilot', name: 'Support Pilot', version: '2.7.0',
    publisher: { name: 'Helpdeskify', verified: true },
    description: 'Answers customer tickets from your docs and past resolutions; hands off to humans with full context.',
    category: 'support', tags: ['customer support', 'tickets'],
    capabilities: ['answer tickets', 'search knowledge base', 'escalate to humans'],
    model: 'claude-sonnet-5', permissions: ['crm:read', 'crm:write'],
    pricing: { model: 'per_call', pricePerCall: 0.08 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 27600, ratings: { avg: 4.3, count: 2210 }, updatedAt: '2026-06-25' },
  },
  {
    id: 'sql-analyst', name: 'SQL Analyst', version: '1.9.3',
    publisher: { name: 'QueryCraft', verified: false },
    description: 'Turns business questions into SQL, runs them read-only against your warehouse, and explains the results.',
    category: 'data', tags: ['sql', 'analytics', 'warehouse'],
    capabilities: ['write SQL', 'analyze results', 'build dashboards'],
    model: 'claude-sonnet-5', permissions: ['files:read'],
    pricing: { model: 'subscription', monthly: 29 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 6900, ratings: { avg: 4.5, count: 160 }, updatedAt: '2026-05-30' },
  },
  {
    id: 'meeting-scribe', name: 'Meeting Scribe', version: '0.9.0',
    publisher: { name: 'Notably', verified: false },
    description: 'Joins calls, takes structured notes, extracts action items and schedules the follow-ups it owns.',
    category: 'productivity', tags: ['meetings', 'notes', 'calendar'],
    capabilities: ['transcribe meetings', 'extract action items', 'schedule follow-ups'],
    model: 'claude-haiku-4-5', permissions: ['calendar:read', 'calendar:write'],
    pricing: { model: 'free' },
    security: { sandboxed: true, scanPassed: false },
    stats: { installs: 3100, ratings: { avg: 4.9, count: 7 }, updatedAt: '2026-06-01' },
  },
  {
    id: 'growth-writer', name: 'Growth Writer', version: '1.2.0',
    publisher: { name: 'Loop Marketing', verified: false },
    description: 'Drafts landing pages, launch emails and social posts in your brand voice, learning from what converted.',
    category: 'marketing', tags: ['copywriting', 'landing pages', 'email'],
    capabilities: ['write marketing copy', 'A/B variants', 'brand voice matching'],
    model: 'claude-sonnet-5', permissions: ['files:read', 'files:write'],
    pricing: { model: 'subscription', monthly: 19 },
    security: { sandboxed: false, scanPassed: false },
    stats: { installs: 5200, ratings: { avg: 3.9, count: 410 }, updatedAt: '2025-11-10' },
  },
  {
    id: 'deal-closer', name: 'Deal Closer', version: '2.0.0',
    publisher: { name: 'PipelineAI', verified: true },
    description: 'Works your CRM pipeline: qualifies leads, sends outreach, books calls, and charges only on closed revenue.',
    category: 'sales', tags: ['crm', 'outreach', 'pipeline'],
    capabilities: ['qualify leads', 'send outreach', 'book meetings'],
    model: 'claude-fable-5', permissions: ['crm:read', 'crm:write', 'email:send', 'calendar:write'],
    pricing: { model: 'revshare', sharePct: 5 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 4400, ratings: { avg: 4.1, count: 260 }, updatedAt: '2026-06-10' },
  },
  {
    id: 'ops-runbook', name: 'Ops Runbook', version: '1.0.4',
    publisher: { name: 'Midnight Ops', verified: false },
    description: 'Executes your incident runbooks: gathers diagnostics, proposes the remediation, and runs it on approval.',
    category: 'devops', tags: ['incidents', 'sre', 'automation'],
    capabilities: ['run diagnostics', 'execute runbooks', 'write postmortems'],
    model: 'claude-sonnet-5', permissions: ['shell:exec', 'net:fetch', 'credentials:access'],
    pricing: { model: 'subscription', monthly: 99 },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 1900, ratings: { avg: 4.7, count: 88 }, updatedAt: '2026-06-22' },
  },
  {
    id: 'paper-digest', name: 'Paper Digest', version: '1.1.0',
    publisher: { name: 'Arxiv Tools', verified: false },
    description: 'Summarizes new papers in your field each morning and answers questions grounded in the full text.',
    category: 'research', tags: ['papers', 'arxiv', 'summaries'],
    capabilities: ['summarize papers', 'daily digests', 'grounded Q&A'],
    model: 'claude-haiku-4-5', permissions: ['net:fetch'],
    pricing: { model: 'free' },
    security: { sandboxed: true, scanPassed: true },
    stats: { installs: 15700, ratings: { avg: 4.2, count: 930 }, updatedAt: '2026-06-18' },
  },
];

if (typeof module !== 'undefined') module.exports = { REGISTRY };
